import { z } from 'zod'

import {
  COMMUNITY_SPACE_IDS,
  type CommunitySpaceId,
} from '@/lib/community/constants'
import type { DayTheme } from '@/lib/community/themes'
import { bodyMeetsThemeRequirements } from '@/lib/community/theme-guards'

export const MIN_POST_BODY_CHARS = 100

export const KARMA_PRODUCT_URL_THRESHOLD = 10

/** Matches `public.posts.stage` check constraint. */
export const POST_STAGES = ['idea', 'wireframe', 'beta', 'live'] as const

export type PostStage = (typeof POST_STAGES)[number]

export const POST_STAGE_LABELS: Record<PostStage, string> = {
  idea: 'Idea',
  wireframe: 'Wireframe',
  beta: 'Beta',
  live: 'Live',
}

const spaceEnum = z.enum(
  COMMUNITY_SPACE_IDS as [CommunitySpaceId, ...CommunitySpaceId[]]
)

const stageEnum = z.enum(POST_STAGES)

export const createPostSchema = z
  .object({
    title: z
      .string()
      .trim()
      .min(5, 'Title must be at least 5 characters.')
      .max(200, 'Title must be 200 characters or fewer.'),
    space: spaceEnum,
    stage: stageEnum,
    body: z
      .string()
      .trim()
      .min(MIN_POST_BODY_CHARS, `Body must be at least ${MIN_POST_BODY_CHARS} characters.`),
    productUrl: z.string().trim(),
  })
  .superRefine((data, ctx) => {
    if (data.productUrl.length > 0 && !isValidHttpUrl(data.productUrl)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: 'Enter a valid product URL.',
        path: ['productUrl'],
      })
    }
  })

function isValidHttpUrl(value: string): boolean {
  try {
    const url = new URL(value)
    return url.protocol === 'http:' || url.protocol === 'https:'
  } catch {
    return false
  }
}

export type CreatePostInput = z.infer<typeof createPostSchema>

/** Row shape for `public.posts` inserts (slug generated by DB trigger). */
export type PostInsert = {
  author_id: string
  title: string
  body: string
  space: CommunitySpaceId
  stage: PostStage
  product_url: string | null
  image_urls: string[] | null
}

export function validatePostForTheme(
  input: CreatePostInput,
  theme: DayTheme
): string | null {
  if (!bodyMeetsThemeRequirements(input.body, theme)) {
    return `${theme.title} requires numerical context in your post body.`
  }
  return null
}
