import type { CommunitySpaceId } from '@/lib/community/constants'

export const SPACE_MARKDOWN_TEMPLATES: Record<
  Extract<CommunitySpaceId, 'validate' | 'build' | 'launch'>,
  string
> = {
  validate: `Problem I observed: ...
Who has this problem: ...
Current workarounds: ...
My proposed solution: ...
My biggest uncertainty: ...`,
  build: `What I'm building: ...
My current stage: ...
Specific decision I need help with: ...
Options I'm considering: ...`,
  launch: `Product: ...
Who it's for: ...
Problem it solves: ...
Live link: ...
Early traction: ...
What feedback I need: ...`,
}

export function getSpaceMarkdownTemplate(
  spaceId: CommunitySpaceId
): string | null {
  if (spaceId === 'grow') return null
  return SPACE_MARKDOWN_TEMPLATES[spaceId]
}
