import type { Metadata } from 'next'
import Link from 'next/link'

import { ValifyeNavbar } from '@/components/valifye-navbar'
import type { ShowcaseTemplate } from '@/lib/marketingShowcase'
import { getAllShowcaseReports } from '@/lib/marketingShowcase'
import { buildCanonical } from '@/lib/seo'

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://valifye.com'

function formatTemplateLabel(template: ShowcaseTemplate): string {
  return template
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

export const dynamic = 'force-dynamic'
export const revalidate = 0

export const metadata: Metadata = {
  title: 'Showcase | Valifye Live Intelligence Reports',
  description:
    'Real forensic intelligence reports generated by Valifye. See exactly what a BUILD / PIVOT / KILL audit looks like before you commit.',
  alternates: {
    canonical: buildCanonical('/showcase')
  },
  openGraph: {
    title: 'Showcase | Valifye Live Intelligence Reports',
    description: 'Real forensic reports. See what a BUILD / PIVOT / KILL audit looks like.',
    url: `${SITE_URL}/showcase`,
    type: 'website'
  }
}

export default async function ShowcaseHubPage() {
  const reports = await getAllShowcaseReports()

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white">
      <ValifyeNavbar />
      <main className="min-h-screen">
        <section className="border-b border-[#1f2937] px-6 pb-12 pt-24 md:px-12 lg:px-24">
          <p className="mb-4 font-mono text-[11px] uppercase tracking-[0.2em] text-[#6b7280]">
            Live Intelligence · Anonymized
          </p>
          <h1 className="mb-4 text-4xl font-black leading-tight md:text-5xl">Showcase</h1>
          <p className="max-w-xl text-lg text-[#9ca3af]">
            Real forensic reports generated by Valifye. Every audit is anonymized but the
            intelligence is live — see exactly what you get before you commit.
          </p>
        </section>

        <section className="px-6 py-12 md:px-12 lg:px-24">
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            {reports.map((report) => (
              <Link
                key={report.slug}
                href={`/showcase/${report.slug}`}
                className="group block rounded-xl border border-[#1f2937] bg-[#0d0d0d] p-6 transition-all duration-200 hover:border-[#f5a623]/40 hover:bg-[#111111]"
              >
                {report.forensicVerdict ? (
                  <span className="mb-3 inline-block rounded bg-[#f5a623] px-2 py-0.5 font-mono text-[10px] font-black uppercase tracking-[0.15em] text-black">
                    {report.forensicVerdict}
                  </span>
                ) : null}

                <h2 className="mb-2 text-xl font-bold leading-snug text-white transition-colors group-hover:text-[#f5a623]">
                  {report.title}
                </h2>

                <p className="mb-2 font-mono text-[11px] uppercase tracking-wider text-[#6b7280]">
                  {formatTemplateLabel(report.template)}
                </p>

                <div className="mt-4 flex items-center gap-1 font-mono text-[11px] tracking-wide text-[#f5a623]">
                  READ REPORT
                  <span className="transition-transform group-hover:translate-x-1">→</span>
                </div>
              </Link>
            ))}
          </div>

          {reports.length === 0 ? (
            <p className="font-mono text-sm text-[#6b7280]">No showcase reports available yet.</p>
          ) : null}
        </section>
      </main>
    </div>
  )
}
