import type { Metadata } from 'next'
import Link from 'next/link'
import {
  ArrowRight,
  ArrowUpRight,
  Clock,
  Crosshair,
  Map as MapIcon,
  Rocket,
  Scale,
  Shield,
  Skull,
  Sparkles,
  type LucideIcon
} from 'lucide-react'
import { MarketingShell } from '@/components/MarketingShell'
import {
  getShowcaseList,
  type MarketingShowcaseReport,
  type ShowcaseTemplate
} from '@/lib/marketingShowcase'
import { cn } from '@/lib/utils'

const SITE_URL = 'https://valifye.com'
const PAGE_URL = `${SITE_URL}/reports`

const PAGE_DESCRIPTION =
  'The Intelligence Pathfinder. Choose your battleground: forensic local market audits for brick-and-mortar founders, or competitive intelligence for SaaS and AI builders.'

export const revalidate = 300

export const metadata: Metadata = {
  title: 'Intelligence Pathfinder | Forensic Business Intelligence',
  description: PAGE_DESCRIPTION,
  openGraph: {
    title: 'Intelligence Pathfinder | Forensic Business Intelligence',
    description: PAGE_DESCRIPTION,
    type: 'website',
    url: PAGE_URL
  },
  alternates: {
    canonical: PAGE_URL
  }
}

const LOCAL_TYPES: ShowcaseTemplate[] = ['scout', 'scout_pivot', 'arsenal']
const DIGITAL_TYPES: ShowcaseTemplate[] = ['battlefield', 'pivot']

const ALL_TYPES: ShowcaseTemplate[] = [
  ...LOCAL_TYPES,
  ...DIGITAL_TYPES,
  'risk'
]

type TemplateChipMeta = {
  label: string
  Icon: LucideIcon
  className: string
}

const TEMPLATE_CHIP: Record<ShowcaseTemplate, TemplateChipMeta> = {
  scout: {
    label: 'Local Scout',
    Icon: MapIcon,
    className: 'border-amber-400/40 bg-amber-500/[0.08] text-amber-200'
  },
  scout_pivot: {
    label: 'Local Recovery',
    Icon: Skull,
    className: 'border-rose-400/40 bg-rose-500/[0.08] text-rose-200'
  },
  arsenal: {
    label: 'Execution Arsenal',
    Icon: Rocket,
    className: 'border-emerald-400/40 bg-emerald-500/[0.08] text-emerald-200'
  },
  battlefield: {
    label: 'Digital Battlefield',
    Icon: Crosshair,
    className: 'border-cyan-400/40 bg-cyan-500/[0.08] text-cyan-200'
  },
  pivot: {
    label: 'Pivot Playbook',
    Icon: Scale,
    className: 'border-indigo-400/40 bg-indigo-500/[0.08] text-indigo-200'
  },
  risk: {
    label: 'Risk Register',
    Icon: Shield,
    className: 'border-zinc-500/40 bg-zinc-500/[0.08] text-zinc-200'
  }
}

function formatRelative(iso?: string): string {
  if (!iso) return 'Forensic audit'
  const date = new Date(iso)
  if (Number.isNaN(date.getTime())) return 'Forensic audit'
  const diffMs = Date.now() - date.getTime()
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24))
  if (diffDays <= 0) return 'today'
  if (diffDays === 1) return 'yesterday'
  if (diffDays < 7) return `${diffDays} days ago`
  if (diffDays < 30) return `${Math.floor(diffDays / 7)} wk ago`
  if (diffDays < 365) return `${Math.floor(diffDays / 30)} mo ago`
  return `${Math.floor(diffDays / 365)} yr ago`
}

export default async function IntelligencePathfinderPage() {
  const reports = await getShowcaseList(ALL_TYPES)

  const localCount = reports.filter((r) =>
    LOCAL_TYPES.includes(r.template)
  ).length
  const digitalCount = reports.filter((r) =>
    DIGITAL_TYPES.includes(r.template)
  ).length
  const totalCount = reports.length

  const latest = reports.slice(0, 4)

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: 'Intelligence Pathfinder',
    description: PAGE_DESCRIPTION,
    url: PAGE_URL,
    hasPart: [
      {
        '@type': 'WebPage',
        name: 'Local Market Intelligence Center',
        url: `${SITE_URL}/local-market-scout`
      },
      {
        '@type': 'WebPage',
        name: 'Digital Battlefield Hub',
        url: `${SITE_URL}/digital-battlefield`
      }
    ]
  }

  return (
    <MarketingShell className="max-w-[1280px] gap-20">
      <script
        type="application/ld+json"
        suppressHydrationWarning
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <section className="space-y-6 text-center md:text-left">
        <p className="inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.32em] text-primary">
          <Sparkles className="h-3.5 w-3.5" />
          Intelligence Pathfinder
        </p>
        <h1 className="font-serif text-4xl font-black leading-[1.05] tracking-tight text-zinc-50 md:text-6xl lg:text-[5rem]">
          Access the World&apos;s Most Detailed
          <span className="block text-primary">
            Forensic Business Intelligence.
          </span>
        </h1>
        <p className="max-w-3xl text-base leading-relaxed text-zinc-400 md:text-lg">
          {PAGE_DESCRIPTION} Every report is generated by the Valifye intelligence
          engine, validated against street-level signals, and engineered to
          eliminate guesswork before you spend a dollar.
        </p>
        <div className="flex flex-wrap items-center justify-center gap-3 pt-2 text-[10px] font-semibold uppercase tracking-[0.22em] text-zinc-500 md:justify-start">
          <span className="rounded-full border border-zinc-700/60 bg-zinc-900/50 px-3 py-1">
            {totalCount} Forensic Audits Indexed
          </span>
          <span className="rounded-full border border-amber-500/30 bg-amber-500/[0.06] px-3 py-1 text-amber-200">
            {localCount} Local
          </span>
          <span className="rounded-full border border-cyan-500/30 bg-cyan-500/[0.06] px-3 py-1 text-cyan-200">
            {digitalCount} Digital
          </span>
        </div>
      </section>

      <section className="space-y-4">
        <div className="flex items-center justify-between border-b border-zinc-800/80 pb-3 text-[10px] font-semibold uppercase tracking-[0.28em] text-zinc-500">
          <span>Choose Your Battleground</span>
          <span className="hidden text-zinc-600 md:inline">Two divisions. One engine.</span>
        </div>
        <div className="grid gap-6 lg:grid-cols-2">
          <BentoCard
            href="/local-market-scout"
            eyebrow="Local Market Scout"
            title="For Brick & Mortar Founders."
            description="Forensic capex, AOV, local demand, saturation autopsies, recovery vectors, and 90-day execution roadmaps for any physical operator."
            Icon={MapIcon}
            ctaLabel="Enter Local Intelligence"
            countLabel={`${localCount} forensic audits`}
            theme="forensic"
          />
          <BentoCard
            href="/digital-battlefield"
            eyebrow="Digital Battlefield"
            title="For SaaS & AI Builders."
            description="Competitor maps, pricing whitespace, feature gaps, complaint mining, and blue-ocean pivot playbooks against entrenched incumbents."
            Icon={Shield}
            ctaLabel="Enter the Battlefield"
            countLabel={`${digitalCount} forensic audits`}
            theme="cyber"
          />
        </div>
      </section>

      <section className="space-y-6">
        <header className="flex flex-col gap-2 border-b border-zinc-800/80 pb-4 md:flex-row md:items-end md:justify-between">
          <div className="space-y-1">
            <p className="inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.28em] text-primary">
              <Clock className="h-3.5 w-3.5" />
              Latest Intelligence
            </p>
            <h2 className="font-serif text-2xl font-black tracking-tight text-zinc-50 md:text-3xl">
              Newest forensic audits across every division.
            </h2>
          </div>
          <Link
            href="/showcase"
            className="inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.22em] text-zinc-400 transition-colors hover:text-primary"
          >
            View archive
            <ArrowRight className="h-3.5 w-3.5" />
          </Link>
        </header>

        {latest.length === 0 ? (
          <div className="rounded-md border border-dashed border-zinc-800 bg-slate-900/30 px-6 py-10 text-center text-sm text-zinc-500">
            No forensic audits indexed yet. The intelligence engine is warming up.
          </div>
        ) : (
          <ol className="divide-y divide-zinc-800/80 overflow-hidden rounded-lg border border-zinc-800/80 bg-slate-900/30">
            {latest.map((report, index) => (
              <LatestRow key={report.slug} report={report} index={index} />
            ))}
          </ol>
        )}
      </section>
    </MarketingShell>
  )
}

type BentoTheme = 'forensic' | 'cyber'

type BentoCardProps = {
  href: string
  eyebrow: string
  title: string
  description: string
  Icon: LucideIcon
  ctaLabel: string
  countLabel: string
  theme: BentoTheme
}

function BentoCard({
  href,
  eyebrow,
  title,
  description,
  Icon,
  ctaLabel,
  countLabel,
  theme
}: BentoCardProps) {
  const isCyber = theme === 'cyber'

  return (
    <Link
      href={href}
      className={cn(
        'group relative overflow-hidden rounded-xl border bg-slate-950/40 p-8 transition-all duration-300 md:p-10',
        'hover:-translate-y-1',
        isCyber
          ? 'border-cyan-500/25 hover:border-cyan-400/60 hover:shadow-[0_0_60px_-12px_rgba(34,211,238,0.55),0_0_2px_rgba(99,102,241,0.5)]'
          : 'border-amber-500/25 hover:border-amber-400/60 hover:shadow-[0_0_60px_-12px_rgba(245,158,11,0.55),0_0_2px_rgba(244,63,94,0.5)]'
      )}
    >
      <div
        className={cn(
          'pointer-events-none absolute inset-0 -z-10 opacity-90 transition-opacity duration-500 group-hover:opacity-100',
          isCyber
            ? 'bg-gradient-to-br from-cyan-950/50 via-slate-950 to-indigo-950/40'
            : 'bg-gradient-to-br from-amber-950/40 via-slate-950 to-rose-950/40'
        )}
        aria-hidden
      />
      <span
        className={cn(
          'pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full blur-3xl transition-opacity duration-500',
          isCyber
            ? 'bg-cyan-500/20 group-hover:bg-cyan-400/30'
            : 'bg-amber-500/20 group-hover:bg-amber-400/30'
        )}
        aria-hidden
      />

      <div className="relative flex h-full flex-col gap-8">
        <header className="flex items-start justify-between gap-4">
          <div
            className={cn(
              'flex h-16 w-16 items-center justify-center rounded-lg border',
              isCyber
                ? 'border-cyan-400/40 bg-cyan-500/[0.08] text-cyan-200 shadow-[0_0_30px_-8px_rgba(34,211,238,0.55)]'
                : 'border-amber-400/40 bg-amber-500/[0.08] text-amber-200 shadow-[0_0_30px_-8px_rgba(245,158,11,0.55)]'
            )}
          >
            <Icon className="h-8 w-8" strokeWidth={1.75} />
          </div>
          <span
            className={cn(
              'rounded-full border px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.22em]',
              isCyber
                ? 'border-cyan-400/30 bg-slate-950/40 text-cyan-200'
                : 'border-amber-400/30 bg-slate-950/40 text-amber-200'
            )}
          >
            {countLabel}
          </span>
        </header>

        <div className="space-y-3">
          <p
            className={cn(
              'text-[10px] font-semibold uppercase tracking-[0.32em]',
              isCyber ? 'text-cyan-300' : 'text-amber-300'
            )}
          >
            {eyebrow}
          </p>
          <h3 className="font-serif text-3xl font-black leading-tight tracking-tight text-zinc-50 md:text-4xl">
            {title}
          </h3>
          <p className="max-w-xl text-sm leading-relaxed text-zinc-400 md:text-base">
            {description}
          </p>
        </div>

        <footer
          className={cn(
            'mt-auto inline-flex items-center justify-between gap-3 border-t pt-6 text-sm font-semibold uppercase tracking-[0.18em]',
            isCyber
              ? 'border-cyan-500/20 text-cyan-200'
              : 'border-amber-500/20 text-amber-200'
          )}
        >
          <span>{ctaLabel}</span>
          <span
            className={cn(
              'inline-flex h-10 w-10 items-center justify-center rounded-full border transition-all',
              isCyber
                ? 'border-cyan-400/40 bg-cyan-500/[0.08] text-cyan-100 group-hover:bg-cyan-400 group-hover:text-slate-950'
                : 'border-amber-400/40 bg-amber-500/[0.08] text-amber-100 group-hover:bg-amber-400 group-hover:text-slate-950'
            )}
          >
            <ArrowUpRight className="h-5 w-5 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
          </span>
        </footer>
      </div>
    </Link>
  )
}

function LatestRow({
  report,
  index
}: {
  report: MarketingShowcaseReport
  index: number
}) {
  const chip = TEMPLATE_CHIP[report.template]
  const ChipIcon = chip.Icon

  return (
    <li className="group">
      <Link
        href={`/showcase/${report.slug}`}
        className="flex flex-col gap-4 px-5 py-5 transition-colors hover:bg-slate-900/60 md:flex-row md:items-center md:gap-6 md:px-6"
      >
        <span className="flex shrink-0 items-center gap-3 font-mono text-[10px] uppercase tracking-[0.28em] text-zinc-500">
          <span className="tabular-nums">{String(index + 1).padStart(2, '0')}</span>
          <span
            className={cn(
              'inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-[10px] font-semibold uppercase tracking-[0.22em]',
              chip.className
            )}
          >
            <ChipIcon className="h-3 w-3" />
            {chip.label}
          </span>
        </span>

        <div className="min-w-0 flex-1">
          <h3 className="font-serif text-base font-bold tracking-tight text-zinc-100 transition-colors group-hover:text-white md:text-lg">
            {report.title}
          </h3>
          {report.forensicVerdict && (
            <p className="mt-1 line-clamp-2 text-sm leading-relaxed text-zinc-400">
              {report.forensicVerdict}
            </p>
          )}
        </div>

        <div className="flex shrink-0 items-center gap-4 text-[10px] font-semibold uppercase tracking-[0.22em] text-zinc-500">
          <span>{formatRelative(report.updatedAt)}</span>
          <span className="inline-flex items-center gap-1 text-zinc-300 transition-colors group-hover:text-primary">
            Open
            <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" />
          </span>
        </div>
      </Link>
    </li>
  )
}
