import type { Metadata } from 'next'
import {
  MapPin,
  Rocket,
  Skull
} from 'lucide-react'
import { MarketingShell } from '@/components/MarketingShell'
import { ShowcaseSection } from '@/components/showcase/ShowcaseSection'
import { getShowcaseList } from '@/lib/marketingShowcase'

const SITE_URL = 'https://valifye.com'
const HUB_URL = `${SITE_URL}/local-market-scout`

const PAGE_DESCRIPTION =
  'Forensic local market audits, recovery playbooks, and 90-day execution roadmaps for brick-and-mortar, food, retail, and service operators. Every report is generated by the Valifye intelligence engine.'

export const revalidate = 300

export const metadata: Metadata = {
  title: 'Local Market Intelligence Center | Forensic Business Audits',
  description: PAGE_DESCRIPTION,
  openGraph: {
    title: 'Local Market Intelligence Center | Forensic Business Audits',
    description: PAGE_DESCRIPTION,
    type: 'website',
    url: HUB_URL
  },
  alternates: {
    canonical: HUB_URL
  }
}

export default async function LocalMarketIntelligenceCenterPage() {
  const reports = await getShowcaseList(['scout', 'scout_pivot', 'arsenal'])

  const primaryAudits = reports.filter((r) => r.template === 'scout')
  const recoveryPlans = reports.filter((r) => r.template === 'scout_pivot')
  const executionRoadmaps = reports.filter((r) => r.template === 'arsenal')

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: 'Local Market Intelligence Center',
    description: PAGE_DESCRIPTION,
    url: HUB_URL,
    hasPart: reports.map((report) => ({
      '@type': 'Report',
      name: report.title,
      url: `${SITE_URL}/showcase/${report.slug}`,
      abstract: report.forensicVerdict
    }))
  }

  return (
    <MarketingShell className="max-w-[1280px] gap-16">
      <script
        type="application/ld+json"
        suppressHydrationWarning
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <header className="space-y-5 border-b border-zinc-800/80 pb-10">
        <p className="inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.28em] text-amber-400/90">
          <MapPin className="h-3.5 w-3.5" />
          Forensic Local Intelligence
        </p>
        <h1 className="font-serif text-3xl font-black tracking-tight text-zinc-50 md:text-5xl">
          Local Market Intelligence Center
        </h1>
        <p className="max-w-3xl text-sm leading-relaxed text-zinc-400 md:text-base">
          {PAGE_DESCRIPTION}
        </p>
        <div className="flex flex-wrap items-center gap-3 pt-2 text-[10px] font-semibold uppercase tracking-[0.22em] text-zinc-500">
          <span className="rounded-full border border-amber-500/30 bg-amber-500/[0.06] px-3 py-1 text-amber-200">
            {primaryAudits.length} Scout Audits
          </span>
          <span className="rounded-full border border-rose-500/30 bg-rose-500/[0.06] px-3 py-1 text-rose-200">
            {recoveryPlans.length} Recovery Plans
          </span>
          <span className="rounded-full border border-emerald-500/30 bg-emerald-500/[0.06] px-3 py-1 text-emerald-200">
            {executionRoadmaps.length} Execution Roadmaps
          </span>
        </div>
      </header>

      <ShowcaseSection
        title="Primary Forensic Audits"
        description="Street-level demand, capex, AOV, and saturation autopsies for a single market. The entry point for any local operator."
        accentClassName="text-amber-400/90"
        iconColorClassName="text-amber-300"
        icon={<MapPin className="h-3.5 w-3.5" />}
        reports={primaryAudits}
        emptyState="No primary Local Market Scout reports indexed yet."
      />

      <ShowcaseSection
        title="Recovery & Turnaround Plans"
        description="Forensic autopsies of failing operations with two recovery vectors, new unit economics, and a transition roadmap."
        accentClassName="text-rose-400/90"
        iconColorClassName="text-rose-300"
        icon={<Skull className="h-3.5 w-3.5" />}
        reports={recoveryPlans}
        emptyState="No recovery or turnaround plans indexed yet."
      />

      <ShowcaseSection
        title="90-Day Execution Roadmaps"
        description="Setup → Launch → Scale playbooks with the Mom Test discovery script and the first 50 buyers tactics."
        accentClassName="text-emerald-400/90"
        iconColorClassName="text-emerald-300"
        icon={<Rocket className="h-3.5 w-3.5" />}
        reports={executionRoadmaps}
        emptyState="No execution roadmaps indexed yet."
      />
    </MarketingShell>
  )
}
